spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://healtrip.postgres.database.azure.com:5432/heal_trip?currentSchema=heal_trip_atakan
    username: codewizards_admin
    password: karamTeam07.