name: Deploy App to Azure

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev


jobs:
  build:
    runs-on: windows-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-app
          path: ${{ github.workspace }}/target/*.jar
  deploy:
      runs-on: windows-latest
      needs: build
      steps:
        - name: Download Artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: spring-boot-app
        - name: Deploy to Azure
          uses: azure/webapps-deploy@v2
          with:
            app-name: healtrip
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: '*.jar'
